CREATE TABLE tflLookups(
   code         VARCHAR(11) NOT NULL PRIMARY KEY
  ,station      VARCHAR(33) NOT NULL
);
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBST','Baker Street');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCHX','Charing Cross');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUEAC','Elephant & Castle');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUEMB','Embankment');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUERB','Edgware Road Bakerloo');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHAW','Harrow & Wealdstone');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHSN','Harlesden');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUKEN','Kenton');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUKPK','Kilburn Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUKSL','Kensal Green');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLULBN','Lambeth North');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUMVL','Maida Vale');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUMYB','Marylebone');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUNWY','North Wembley');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUOXC','Oxford Circus');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUPAC','Paddington');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUPCC','Piccadilly Circus');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUQPS','Queen''s Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLURGP','Regent''s Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSGP','Stonebridge Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSKT','South Kenton');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWJN','Willesden Junction');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWKA','Warwick Avenue');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWLO','Waterloo');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWYC','Wembley Central');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUADE','Aldgate East');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBBB','Bromley-by-Bow');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBBN','Barbican');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBKG','Barking');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBWR','Bow Road');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUEHM','East Ham');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUERC','Edgware Road Circle Line');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUESQ','Euston Square');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUFCN','Farringdon');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUGHK','Goldhawk Road');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUGPS','Great Portland Street');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHSC','Hammersmith (H&C Line)');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUKSX','King''s Cross St. Pancras');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLULAD','Ladbroke Grove');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLULRD','Latimer Road');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLULVT','Liverpool Street');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUMED','Mile End');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUMGT','Moorgate');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUPAH','Paddington (H&C Line)-Underground');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUPLW','Plaistow');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLURYO','Royal Oak');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSBM','Shepherd''s Bush Market');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSGN','Stepney Green');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUUPK','Upton Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWHM','West Ham');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWLA','Wood Lane');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWPL','Whitechapel');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWSP','Westbourne Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBMY','Bermondsey');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBND','Bond Street');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCGT','Canning Town');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCPK','Canons Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCWR','Canada Water');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCYF','Canary Wharf');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUDOH','Dollis Hill');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUFYR','Finchley Road');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUGPK','Green Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUKBN','Kilburn');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUKBY','Kingsbury');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLULNB','London Bridge');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUNDN','Neasden');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUNGW','North Greenwich');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUQBY','Queensbury');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSJW','St. John''s Wood');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSTD','Stratford');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSTM','Stanmore');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSWC','Swiss Cottage');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSWK','Southwark');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWHP','West Hampstead');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWIG','Willesden Green');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWSM','Westminster');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWYP','Wembley Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBKE','Barkingside');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBKH','Buckhurst Hill');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBLG','Bethnal Green');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBNK','Bank');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCHL','Chancery Lane');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCWL','Chigwell');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUDBN','Debden');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUEAN','East Acton');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUEBY','Ealing Broadway');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUEPG','Epping');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUFLP','Fairlop');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUGFD','Greenford');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUGGH','Grange Hill');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUGTH','Gants Hill');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHBN','Holborn');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHGR','Hanger Lane');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHLT','Hainault');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHPK','Holland Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLULGN','Loughton');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLULGT','Lancaster Gate');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLULYN','Leyton');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLULYS','Leytonstone');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUMBA','Marble Arch');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUNAN','North Acton');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUNBP','Newbury Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUNHG','Notting Hill Gate');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUNHT','Northolt');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUPVL','Perivale');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUQWY','Queensway');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLURBG','Redbridge');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLURSG','Ruislip Gardens');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLURVY','Roding Valley');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSBC','Shepherd''s Bush (Central)');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSNB','Snaresbrook');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSPU','St. Paul''s');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSRP','South Ruislip');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSWF','South Woodford');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUTCR','Tottenham Court Road');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUTHB','Theydon Bois');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWCY','White City');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWOF','Woodford');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWRP','West Ruislip');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWSD','Wanstead');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWTA','West Acton');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUALD','Aldgate');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBKF','Blackfriars');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBWT','Bayswater');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCST','Cannon Street');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUECT','Earl''s Court');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUGTR','Gloucester Road');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHSK','High Street Kensington');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUMMT','Monument');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUMSH','Mansion House');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSJP','St. James''s Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSKS','South Kensington');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSSQ','Sloane Square');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUTMP','Temple');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUTWH','Tower Hill');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUVIC','Victoria');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUACT','Acton Town');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBEC','Becontree');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBSC','Barons Court');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCWP','Chiswick Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUDGE','Dagenham East');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUDGY','Dagenham Heathway');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUECM','Ealing Common');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUEPK','Elm Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUEPY','East Putney');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUFBY','Fulham Broadway');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUGBY','Gunnersbury');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHCH','Hornchurch');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHSD','Hammersmith (Dist&Picc Line)');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUKOY','Kensington (Olympia)');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUKWG','Kew Gardens');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUPSG','Parsons Green');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUPYB','Putney Bridge');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLURMD','Richmond');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLURVP','Ravenscourt Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSFB','Stamford Brook');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSFS','Southfields');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUTNG','Turnham Green');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUUPB','Upminster Bridge');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUUPM','Upminster');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUUPY','Upney');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWBN','West Brompton');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWIM','Wimbledon');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWIP','Wimbledon Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWKN','West Kensington');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUAMS','Amersham');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCAL','Chalfont & Latimer');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCSM','Chesham');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCXY','Croxley');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCYD','Chorleywood');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUEAE','Eastcote');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHGD','Hillingdon');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHOH','Harrow-on-the-Hill');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUICK','Ickenham');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUMPK','Moor Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUNHA','North Harrow');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUNKP','Northwick Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUNOW','Northwood');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUNWH','Northwood Hills');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUPNR','Pinner');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUPRD','Preston Road');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLURKW','Rickmansworth');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLURSM','Ruislip Manor');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLURSP','Ruislip');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLURYL','Rayners Lane');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUUXB','Uxbridge');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWAF','Watford');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWHW','West Harrow');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBLR','Blackhorse Road');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBXN','Brixton');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUEUS','Euston');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUFPK','Finsbury Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHAI','Highbury & Islington');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUPCO','Pimlico');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSKW','Stockwell');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSVS','Seven Sisters');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUTMH','Tottenham Hale');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUVXL','Vauxhall');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWRR','Warren Street');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWWL','Walthamstow Central');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUACY','Archway');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUAGL','Angel');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBLM','Balham');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBOR','Borough');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBTK','Burnt Oak');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBTX','Brent Cross');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBZP','Belsize Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCFM','Chalk Farm');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCND','Colindale');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCPC','Clapham Common');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCPN','Clapham North');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCPS','Clapham South');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCSD','Colliers Wood');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCTN','Camden Town');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUEFY','East Finchley');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUEGW','Edgware');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUFYC','Finchley Central');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUGDG','Goodge Street');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUGGN','Golders Green');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHBT','High Barnet');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHCL','Hendon Central');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHGT','Highgate');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHTD','Hampstead');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUKNG','Kennington');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUKSH','Kentish Town');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLULSQ','Leicester Square');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUMDN','Morden');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUMHL','Mill Hill East');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUMTC','Mornington Crescent');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUODS','Old Street');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUOVL','Oval');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSWN','South Wimbledon');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUTAW','Totteridge & Whetstone');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUTBC','Tooting Bec');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUTBY','Tooting Broadway');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUTFP','Tufnell Park');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWFN','West Finchley');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWOP','Woodside Park');
INSERT INTO tflLookups(code,station) VALUES ('910GENFCOAK','Oakwood Station');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUALP','Alperton');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUASG','Arnos Grove');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUASL','Arsenal');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBDS','Bounds Green');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUBOS','Boston Manor');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCAR','Caledonian Road');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCGN','Covent Garden');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUCKS','Cockfosters');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHNX','Hatton Cross');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHPC','Hyde Park Corner');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHR4','Heathrow Terminal 4');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHR5','Heathrow Terminal 5');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHRC','Heathrow Terminals 1-2-3');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHWC','Hounslow Central');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHWE','Hounslow East');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHWT','Hounslow West');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUHWY','Holloway Road');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUKNB','Knightsbridge');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUMRH','Manor House');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUNEN','North Ealing');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUNFD','Northfields');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUOAK','Oakwood');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUOSY','Osterley');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUPKR','Park Royal');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLURSQ','Russell Square');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSEA','South Ealing');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSGT','Southgate');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSHH','South Harrow');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSUH','Sudbury Hill');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUSUT','Sudbury Town');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUTPN','Turnpike Lane');
INSERT INTO tflLookups(code,station) VALUES ('940GZZLUWOG','Wood Green');